### ISSUE TITLE
FloatingPointError: Predicted boxes or scores contain Inf/NaN. Training has diverged.

### ISSUE THREAD

**Issue by Tongtong-allure** [hustvl/BMaskR-CNN#7]
Hi, when I run configs/bmask_rcnn_R_50_FPN_1x.yaml, it ran 739 iters,then I meet the question as follows,
Traceback (most recent call last):
  File "/home/l547/anaconda3/envs/zt/lib/python3.7/site-packages/detectron2/engine/train_loop.py", line 140, in train
    self.run_step()
  File "/home/l547/anaconda3/envs/zt/lib/python3.7/site-packages/detectron2/engine/train_loop.py", line 226, in run_step
    loss_dict = self.model(data)
  File "/home/l547/anaconda3/envs/zt/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/l547/anaconda3/envs/zt/lib/python3.7/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 160, in forward
    proposals, proposal_losses = self.proposal_generator(images, features, gt_instances)
  File "/home/l547/anaconda3/envs/zt/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/l547/anaconda3/envs/zt/lib/python3.7/site-packages/detectron2/modeling/proposal_generator/rpn.py", line 449, in forward
    anchors, pred_objectness_logits, pred_anchor_deltas, images.image_sizes
  File "/home/l547/anaconda3/envs/zt/lib/python3.7/site-packages/detectron2/modeling/proposal_generator/rpn.py", line 486, in predict_proposals
    self.training,
  File "/home/l547/anaconda3/envs/zt/lib/python3.7/site-packages/detectron2/modeling/proposal_generator/proposal_utils.py", line 92, in find_top_rpn_proposals
    "Predicted boxes or scores contain Inf/NaN. Training has diverged."
FloatingPointError: Predicted boxes or scores contain Inf/NaN. Training has diverged.

I want to know how to address,please?

**Comment by wondervictor** [comment]
Hi @Tongtong-allure, can you provide some details about your training setting

**Comment by Tongtong-allure** [comment]
Thanks for your answering, but I have addressed by adjusting the lr.

**Comment by wondervictor** [comment]
Learning rate and batch size (linear scaling rule) should be taken into account when training object detection methods (such as Faster R-CNN, Mask R-CNN, RetinaNet and etc.).
